CREATE DATABASE DAW;
Use DAW;




CREATE TABLE Jugador (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Nom NVARCHAR(50)
	
);

CREATE TABLE Mon (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Nom NVARCHAR(50)
	
);

CREATE TABLE Partida (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	idMon UNIQUEIDENTIFIER NOT NULL,
	Data DATE,
	CONSTRAINT FK_MonPartida FOREIGN KEY (idMon)
		REFERENCES Mon(Id)
	
	
);

CREATE TABLE Objectes (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Nom NVARCHAR(50)
	
);

CREATE TABLE JugadorsPartida (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	idJugador UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT FK_JugadorPartida FOREIGN KEY (idJugador)
		REFERENCES Jugador(Id)
	
);

CREATE TABLE ObjectesPartida (
	idJugadorPartida UNIQUEIDENTIFIER NOT NULL,
	idObjecte UNIQUEIDENTIFIER NOT NULL,
	quant INT,
	PRIMARY KEY(idJugadorPartida, idObjecte),
	CONSTRAINT PK_JugadorPartida FOREIGN KEY (idJugadorPartida)
		REFERENCES JugadorsPartida(Id),
	CONSTRAINT PK_Objecte FOREIGN KEY (idObjecte)
		references Objectes(Id)
);

INSERT INTO Objectes VALUES
(
'1520AD76-E1FA-408A-837D-0600DB0A38A3', 'Moneda'
)

INSERT INTO Jugador VALUES
(
'1520AD76-E1FA-408A-837D-0600DB0A38A6', 'Miquel'
)

INSERT INTO JugadorsPartida VALUES
(
'1520AD76-E1FA-408A-837D-0600DB0A38A5', '1520AD76-E1FA-408A-837D-0600DB0A38A6'
)






